PROJNAME:=client
EXEDIR:=../../../bin/chatroom
LINK_FLAGS:=-L../../../lib -lstdc++ -lconnection -lpthread
COMPILE_FLAGS:=-I../../../include
DEBUG:=Y
COMPILE_FILES:= client.cpp 
include ../../../Makefile-exe
