PROJNAME:=epoll_server
EXEDIR:=../../../bin/echo
LINK_FLAGS:=-L../../../lib -lstdc++ -lconnection
COMPILE_FLAGS:=-I../../../include
DEBUG=Y
COMPILE_FILES:= epoll_server.cpp 
include ../../../Makefile-exe
