PROJNAME:=connection
LIBDIR:=../lib
LINK_FLAGS:=-lstdc++ 
COMPILE_FLAGS:=-I../include
DEBUG:=Y
COMPILE_FILES:= ConnectionException.cpp \
				ConnectionIPV4.cpp \
				ConcurrentServer.cpp \
				SelectServer.cpp \
				PollServer.cpp \
				EPollServer.cpp 
include ../Makefile-so
